### ISSUE TITLE
Minor change for multibot.py to use multiple RSI, TV Buy filters

### ISSUE THREAD

**Issue by M1ch43lV** [TBMoonwalker/3cqsbot#11]
Hi TB,

to use multiple filters as strategy list from the config.ini like this (deal_mode as JSON compliant format)

deal_mode = [{"options": {"time": "5m", "type": "buy_or_strong_buy"}, "strategy": "trading_view"},{"options":{"time":"15m","points":70},"strategy":"rsi"},{"options":{"time":"1h","points":70},"strategy":"rsi"},{"options":{"time":"4h","points":70},"strategy":"rsi"}]

it requires a little change  in the multibot.py:

---------------
  def strategy(self):
        
        if self.config['filter']['deal_mode'] == "signal":
            strategy=[{'strategy':'manual'}]
        else:
==>            strategy=json.loads(self.config['filter']['deal_mode'])
    
        return strategy
------------------

Greetings 
Michael

**Comment by TBMoonwalker** [comment]
@M1cha3l-2022 thanks for your fix. Will be implemented in 1.0.6-alpha
