### ISSUE TITLE
Error when running 3cqsbot.py

### ISSUE THREAD

**Issue by berto-0** [TBMoonwalker/3cqsbot#13]
Having this error when running the main file, I added all values in the config files such as key and secret from 3C.
Thanks for the help

runfile('C:/Users/arnau/3cqsbot/3cqsbot.py', wdir='C:/Users/arnau/3cqsbot')
Traceback (most recent call last):

  File "C:\Users\arnau\3cqsbot\3cqsbot.py", line 40, in <module>
    key=config["commas"]["key"],

  File "C:\Users\arnau\Anaconda3\lib\configparser.py", line 963, in __getitem__
    raise KeyError(key)

KeyError: 'commas'

**Comment by TBMoonwalker** [comment]
have you renamed the config.ini.example to config.ini? If yes, check your line endings, for example with Visual Studio Code or Notepad++

**Comment by berto-0** [comment]
Yes this solved the deal, thanks !
