### ISSUE TITLE
When running 3cqsbot as scheduled task on Windows/Unix prevent starting multiple instances in the same directory  

### ISSUE THREAD

**Issue by M1ch43lV** [TBMoonwalker/3cqsbot#14]
Suggestion: 
When Pythonanywhere is restarted due to maintenance reasons, the script 3cqsbot will not be restarted automatically. 
To restart 3cqsbot, you have to create a scheduled task on an hourly basis, on Pyhtonanywhere.
To avoid multiple concurrent running instances of 3cqsbot, the instance is limited to be started only once.

Here is the code to be put in the beginning of 3cqsbot.py:

##############################################################################
#   Run only one instance of 3cqsbot.py when started as scheduled task in PythonAnywhere   # 
##############################################################################
import os
import fcntl

fh=0
def run_once():
    global fh
    fh=open(os.path.realpath(__file__),'r')
    try:
        fcntl.flock(fh,fcntl.LOCK_EX|fcntl.LOCK_NB)
    except:
        os._exit(0)
run_once()

######################################################
#                       Config                       #
######################################################

**Comment by TBMoonwalker** [comment]
What if you like to run multiple instances on your system?

**Comment by M1ch43lV** [comment]
Hello TB, 
   
  
    limiting to only one instance concerns only users of the Pythonanywhere platform. 
   
   
    
   
  
    The Pythonanywhere feature of scheduled task causes the python script to be repetively started, so if the script does not check that another instance is running, then you have multiple instances of 3cqsbot.py. This causes increasing consumption of CPU usage time, which is due to the plan i chose limited to only 2000s per 24h. 
   
  
    As you can see, I am running scheduled tasks of other bots that consumes CPU power. So I limit every python script to run only one instance. 
   
  
    If I exceed the 2000sec, then my virtual environment will be heavily throttled and the bots are not working fast enough any more. 
   
  
    Best regards 
   
  
    Michael 
   
  
      
    
   
   
   
     TBMoonwalker ***@***.***> hat am 14.03.2022 15:46 geschrieben: 
    
    
     
    
    
     
    
    
   What if you like to run multiple instances on your system?

**Comment by TBMoonwalker** [comment]
Again - you limit it, because of your system or service you use. What if you like to have multiple instances on you computer? In different directories? Then it isn't working, right?

**Comment by M1ch43lV** [comment]
I will check and give you the answerVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: TBMoonwalker ***@***.***> Datum: 14.03.22  16:22  (GMT+01:00) An: TBMoonwalker/3cqsbot ***@***.***> Cc: M1cha3l ***@***.***>, Author ***@***.***> Betreff: Re: [TBMoonwalker/3cqsbot] Code to implement: Allow only one instance of 3cqsbot when run as scheduled task on Pythonanywhere (Issue #14) 
Again - you limit it, because of your system or service you use. What if you like to have multiple instances on you computer? In different directories? Then it isn't working, right?

**Comment by M1ch43lV** [comment]
This is possible. I copied 3cqsbot in two directories 3cqsbotA and 
3cqsbotB. Both running simultanousley with the same name 3cqsbot.py.
As long as 3cqsbot is running in different directories, no problem with 
the suggested code. See screenshot



Here is the reference where I get the code:
https://stackoverflow.com/questions/380870/make-sure-only-a-single-instance-of-a-program-is-running
<https://stackoverflow.com/questions/380870/make-sure-only-a-single-instance-of-a-program-is-running>

Am 14.03.2022 um 16:22 schrieb TBMoonwalker:

**Comment by M1ch43lV** [comment]
Changing the module fcntl to portalocker, because of cross-platform compatiblity (Windows/Unix). Module fcntl was only working for Unix based systems.
To install the module:
pip install portalocker


3cqsbot.py
------------
from signals import Signals
-----------> insert code on the relative beginning of 3cqsbot.py after above line
####################################################################
# Run only one instance of 3cqsbot.py when started as scheduled task  on Windows/Unix # 
####################################################################
import os
import portalocker

fh=0
def run_once():
    global fh
    fh=open(os.path.realpath(file),'r')
    try:
        portalocker.lock(fh,portalocker.LOCK_EX|portalocker.LOCK_NB)
    except:
        os._exit(0)
run_once()
<---- insert end
 ######################################################
#                       Config                       #
######################################################

**Comment by xelalem2022** [comment]
I am trying to run a scheduled task on pythonanywhere with this command

python3.9 /home/Zola/botdirectory/3cqsbot.py but I am getting this error
key=config["commas"]["key"],
File "/usr/local/lib/python3.9/configparser.py", line 960, in getitem
raise KeyError(key)
KeyError: 'commas'

I have set all the required value on the config files
am I missing something
