### ISSUE TITLE
check for < and > sign in the filter setting for symrank, volatility and price action 

### ISSUE THREAD

**Issue by M1ch43lV** [TBMoonwalker/3cqsbot#15]
Following combination of filter settings needed:
use symrank < 100 with volatility filter > 2 and price action > 3
Thanks for adjusting the filter settings

**Comment by M1ch43lV** [comment]
Here a suggestion for this:
Define in config.ini variables for min and max of volatility, price_action and symrank

----modified code for 3cqsbot.py
            # Trigger bot if limits passed
            if tg_output["volatility"] != 0 and tg_output["pair"] in pair_output:
                if (
                    tg_output["volatility"] >= config["filter"].getfloat("volatility_limit_min")
                    and tg_output["volatility"] <= config["filter"].getfloat("volatility_limit_max")
                    and tg_output["price_action"] >= config["filter"].getfloat("price_action_limit_min")
                    and tg_output["price_action"] <= config["filter"].getfloat("price_action_limit_max")
                    and tg_output["symrank"] >= config["filter"].getint("symrank_limit_min")
                    and tg_output["symrank"] <= config["filter"].getint("symrank_limit_max")
                ) or tg_output["action"] == "STOP":

**Comment by TBMoonwalker** [comment]
Implemented in the newest release. Thanks for your support.
