### ISSUE TITLE
Update bot with new symrank pairs also when sleeping 

### ISSUE THREAD

**Issue by M1ch43lV** [TBMoonwalker/3cqsbot#17]
@Gerets raised an important issue. The bot is not updated with symrank changes during sleeping time, if btc_pulse is activated.

Here the fix:
3cqsbot.py: Remove lines 240-242 to allow updating symrank list and symrank STOP signals
```
#   if asyncState.btcbool and config["filter"].getboolean("btc_pulse"):
#       logging.info("Bot stopped - no new signals processed")
#   else:
```
3csbot.py: Remove lines 207-209
```
#                # Send new top 30 for activating the multibot
#                logging.debug("Calling for new symrank stats")
#               await symrank()
```
Put this command instead for line 207-209 because now the bot is constantly updated in the background independent of btc movement: 
```bot.enable()```

multibot.py: Remove line 194 und 212 to prevent activating the bot during sleeping time, when symrank list is updated
```
# self.enable(data)
```

**Comment by TBMoonwalker** [comment]
It doesn't work like that. If Pulse is enabled it is true that no pairs that coming in are updated. But when Pulse starts the bot again, a initial Symrank call is started and the pairs are updated with the lastest symrank list. After that new signals changes the pair list until the next Pulse stop.
