### ISSUE TITLE
futures trading

### ISSUE THREAD

**Issue by seanzyville** [TBMoonwalker/3cqsbot#18]
Hi TB,

Can you enable these options for Futures Trading?

Leverage: x10, x20, x50, x75, x100, x125
Leverage Type: Cross
Stop Loss %:
Stop Loss action:
Stop Loss timeout:

Great work!

Thanks!

**Comment by TBMoonwalker** [comment]
@seanzyville Implemented the code for futures trading. I cannot test this with paper trade, so you have to check, if the implementation works. Please give me feedback on that.
