### ISSUE TITLE
Overriding start/stop of random if pair not existing 

### ISSUE THREAD

**Issue by morgalis** [TBMoonwalker/3cqsbot#19]
Can we override this?
If it is a STOP/START signal which is not from an existing pair a random pair from the initial top 30 Symrank list is used for a new deal.

random pair = risky sometimes

btw great work mate

**Comment by pvdochtend** [comment]
Also a vote from me to stop this behaviour.  (Or make it configurable). Thanks for the great work!

**Comment by TBMoonwalker** [comment]
@pvdochtend @morgalis You can try the latest code now for ignoring random pairs (please see config.ini.example - activate random_pair)

**Comment by pvdochtend** [comment]
Awesome, I will check that out later today!


Op vr 1 apr. 2022 om 17:33 schreef TBMoonwalker ***@***.***>

**Comment by pvdochtend** [comment]
Nice work. Fixed for me.
