### ISSUE TITLE
New undocumented signal provider settings?

### ISSUE THREAD

**Issue by pvdochtend** [TBMoonwalker/3cqsbot#31]
Apparently there is a new setting called "symrank_signal".

I also noticed them in the channel. It would be helpfull if there is documentation about what each setting is doing.
Perhaps in the Readme or a link to an external source where we can read about it?

PS: I hope you don't find comments like this annoying. I really love the product and I eant to help to make it better!

**Comment by TBMoonwalker** [comment]
Updated the documentation about it. Thanks for your suggestion.
