### ISSUE TITLE
Wish: When signal received validate other conditions.

### ISSUE THREAD

**Issue by pvdochtend** [TBMoonwalker/3cqsbot#39]
I would like to have the option to include extra conditions when a signal is received.

Example:
Signal is received
also check if [{"options": {"time": "3m", "points": "100"}, "strategy": "rsi"}] is applicable.

It would be great if that's applicable for single bots.

**Comment by TBMoonwalker** [comment]
You already can set deal strategies? or do I misunderstood something?

**Comment by pvdochtend** [comment]
That's correct. But can I combine it is my question.. Well I didn't wrote it like a question :)

Can I enable multiple lines in the config.ini?
For example:

deal_mode = signal
deal_mode = [{"options": {"time": "3m", "points": "100"}, "strategy": "rsi"}]

or combine it ?
deal_mode = [signal, {"options": {"time": "3m", "points": "100"}, "strategy": "rsi"}]

**Comment by TBMoonwalker** [comment]
This makes no sense, because it is always reacting to the signal. If you change from signal to a 3comma configuration, it just mean that it isn't starting the deal not asap. It is written down in the readme.

**Comment by pvdochtend** [comment]
Clear. Than I didn't understand it correctly. 

The signal itself is offcourse already creating the (single) bot so adding it to the deal_mode next to some other start conditions has no value.
