### ISSUE TITLE
Only one deal when signal is received

### ISSUE THREAD

**Issue by pvdochtend** [TBMoonwalker/3cqsbot#40]
I want to have only one deal triggered and the bot disabled (or removed when delete_single_bots) when receiving a signal.

It can be possible by passing through the 3commas setting "Open deals & stop".

That would be great.

**Comment by itzwolf** [comment]
I've submitted a pull request to add the open deals and stop request along with the cooldown option.

**Comment by pvdochtend** [comment]
Awesome!! Thanks for the quick response.
