### ISSUE TITLE
[Feature Request] Pair Whitelist

### ISSUE THREAD

**Issue by theskollie** [TBMoonwalker/3cqsbot#69]
**Feature:**
Pair Whitelist Filter - Inverse Blacklist

**What it does:**
When a new signal is received, check if signal pair is on whitelist and proceed.
If pair is not on whitelist, console.log skipped.

**Why?:**
Great for Paper Trading, since it's easier to whitelist the pairs your exchange **has**, instead of mass blacklisting pairs that it doesn't have.
Example: Binance US pairs vs Binance pairs - I'd be blacklisting pairs all day
Also, good for if you only want to run certain pairs when it is optimal conditions to run them (when a signal comes in)

Just an idea, if this is not something you are interested in, feel free to close the issue. Thanks

**Comment by TBMoonwalker** [comment]
Done
