### ISSUE TITLE
Support for conditions TP

### ISSUE THREAD

**Issue by ujai** [TBMoonwalker/3cqsbot#81]
Hi

Any plans to support the new 3commas feature where we can use conditions TP instead of percent TP?

![image](https://user-images.githubusercontent.com/1449698/200625919-9abdd04c-f3c1-414e-8309-52f04d62bdc2.png)

Currently it doesn't seems to be supported:
`Other error occurred: record_invalid Invalid parameters {'take_profit': ["Not available to use 'Take profit' together with 'Deal close condition'"]}.`

Thank you in advance

**Comment by TBMoonwalker** [comment]
sorry, but I do not support the open source version anymore.
